fix: list-all correctly ordered

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,17 +10,32 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
+# Create archive file extension based on OS
+ext="tar.gz"
+if [[ "$(uname)" == "Darwin" ]]; then
+	ext="zip"
+fi
 
-# Download tar.gz file to the download directory
+release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.${ext}"
+
+# Download archive file to the download directory
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+#  Extract contents of archive into the download directory
+if [[ "$ext" == "tar.gz" ]]; then
+	tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+elif [[ "$ext" == "zip" ]]; then
+	unzip -q "$release_file" -d "$ASDF_DOWNLOAD_PATH" || fail "Could not extract $release_file"
+fi
 
 # Remove the tar.gz file since we don't need to keep it
 rm "$release_file"
 
 # Rename the binary to the expected name
-mv "${ASDF_DOWNLOAD_PATH}/podman-remote-static-linux_amd64" "$ASDF_DOWNLOAD_PATH/podman"
+binary_path=podman-remote-static-linux_amd64
+
+if [[ "$(uname)" == "Darwin" ]]; then
+	binary_path="podman-${ASDF_INSTALL_VERSION}/usr/bin/podman"
+fi
+
+mv "${ASDF_DOWNLOAD_PATH}/${binary_path}" "$ASDF_DOWNLOAD_PATH/podman"
